version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:12.16.1
      
orbs:
  aws-cli: circleci/aws-cli@1.3.2
  aws-ecr: circleci/aws-ecr@0.0.2
 
jobs:
  build:
    executor: node
    steps:
      - checkout
      - setup_remote_docker
      - run: ls -al && docker images
     
workflows:
  build:
    jobs:
      - build
      - aws-ecr/build_and_push_image:
          requires:
            - build
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "sample-ecr"
          region: ${AWS_DEFAULT_REGION}
          tag: "latest"
