version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:12.16.1
      
orbs:
  aws-cli: circleci/aws-cli@1.3.2
 
commands:
  build_node_app:
    description: "Build sample node.js app"
    steps:
      - run: npm install & npm install forever -g
  image_push:
    description: "push image to ecr"
    steps:
      - run: 
          command: |
            aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 547961105129.dkr.ecr.ap-northeast-2.amazonaws.com
            docker build -t sample-ecr .
            docker tag sample-ecr:latest 547961105129.dkr.ecr.ap-northeast-2.amazonaws.com/sample-ecr:latest
            docker push 547961105129.dkr.ecr.ap-northeast-2.amazonaws.com/sample-ecr:latest
            
      
jobs:
  build:
    executor: node
    steps:
      - checkout
      - build_node_app
      - run: docker images
