version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:12.16.1

orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
  aws-ecs: circleci/aws-ecs@0.0.10

jobs:
  checkout:
    executor: default
    steps:
      - checkout

workflows:
  build_and_deploy:
    jobs:
      - checkout
      - aws-ecr/build_and_push_image:
          requires:
            - checkout
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "sample-ecr"
          region: ${AWS_DEFAULT_REGION}
          tag: "latest"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          aws-region: ${AWS_DEFAULT_REGION}
          family: "${AWS_ECS_FAMILY_NAME}" # task definition name
          cluster-name: "${AWS_ECS_CLUSTER_NAME}" # cluster name
          service-name: "${AWS_ECS_SERVICE_NAME}" # service name
          container-image-name-updates: "container=node,image-and-tag=${AWS_IMAGE_URL}" # container name & image url
